name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipline:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: build project prod
        run: npm run build:pd
        if: always()
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run unit
        if: always()